# Generated by Django 3.2.8 on 2021-10-14 15:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ampurcode', models.CharField(max_length=2)),
                ('ampurname', models.CharField(max_length=155)),
                ('ampurcodefull', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Cchangwat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changwatcode', models.CharField(max_length=2)),
                ('changwatname', models.CharField(max_length=155)),
                ('zonecode', models.CharField(max_length=2)),
                ('changwatname_en', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Ctambon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamboncode', models.CharField(max_length=2)),
                ('tambonname', models.CharField(max_length=155)),
                ('tamboncodefull', models.CharField(max_length=6)),
                ('ampurcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campur')),
                ('changwatcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cchangwat')),
            ],
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Savecmpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('1', 'ชาย'), ('2', 'หญิง')], default='ชาย', max_length=10)),
                ('age', models.IntegerField()),
                ('id_card', models.CharField(max_length=15)),
                ('mobile_phone', models.CharField(max_length=10)),
                ('mobile_partner', models.CharField(blank=True, max_length=10, null=True)),
                ('date_arrive', models.DateField(default=datetime.date.today)),
                ('date_leave', models.DateField(default=datetime.date.today)),
                ('moo', models.CharField(blank=True, max_length=255, null=True)),
                ('house', models.CharField(max_length=255)),
                ('vaccine_pic', models.ImageField(default='default.jpg', upload_to='vaccine_pic')),
                ('sickness', models.ImageField(default='default.jpg', upload_to='sickness')),
                ('lab', models.ImageField(default='default.jpg', upload_to='lab')),
                ('input_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cchangwat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cchangwat')),
                ('campur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.campur')),
                ('ctambon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ctambon')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.duty')),
            ],
        ),
        migrations.AddField(
            model_name='campur',
            name='changwatcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cchangwat'),
        ),
    ]
