# Generated by Django 3.2.5 on 2021-10-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campur',
            name='ampurcodefull',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='savecmpo',
            name='lab',
            field=models.ImageField(blank=True, upload_to='lab/'),
        ),
        migrations.AlterField(
            model_name='savecmpo',
            name='sickness',
            field=models.ImageField(blank=True, upload_to='sickness/'),
        ),
        migrations.AlterField(
            model_name='savecmpo',
            name='vaccine_pic',
            field=models.ImageField(blank=True, upload_to='vaccine_pic/'),
        ),
    ]
