# Generated by Django 3.2.8 on 2021-10-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211017_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savecmpo',
            name='lab',
            field=models.ImageField(default='default.jpg', upload_to='lab/'),
        ),
        migrations.AlterField(
            model_name='savecmpo',
            name='sickness',
            field=models.ImageField(default='default.jpg', upload_to='sickness/'),
        ),
        migrations.AlterField(
            model_name='savecmpo',
            name='vaccine_pic',
            field=models.ImageField(default='default.jpg', upload_to='vaccine_pic/'),
        ),
    ]
